export const members = [
  {
    id: '1',
    name: 'Christian Nwamba',
    handle: '@christian',
    avatarUrl: 'https://bit.ly/code-beast',
    status: 'active',
    message: 'Some message',
    lastSeen: 'just now',
  },
  {
    id: '2',
    name: 'Kent C. Dodds',
    handle: '@kent',
    avatarUrl: 'https://bit.ly/kent-c-dodds',
    status: 'active',
    message: 'Some message',
    lastSeen: '2hr ago',
  },
  {
    id: '3',
    name: 'Prosper Otemuyiwa',
    handle: '@prosper',
    avatarUrl: 'https://bit.ly/prosper-baba',
    status: 'active',
    message: 'Some message',
    lastSeen: '3hr ago',
  },
  {
    id: '4',
    name: 'Ryan Florence',
    handle: '@ryan',
    avatarUrl: 'https://bit.ly/ryan-florence',
    status: 'active',
    message: 'Some message',
    lastSeen: '4hr ago',
  },
  {
    id: '5',
    name: 'Segun Adebayo',
    handle: '@segun',
    avatarUrl: 'https://bit.ly/sage-adebayo',
    status: 'inactive',
    message: 'Some message',
    lastSeen: '5hr ago',
  },
]
